host: 0.0.0.0
port: 8317
auth-dir: ./auths
proxy-url: ""
request-retry: 0
management-key: ""
allow-remote-management: false
debug: false
request-log: true
usage-statistics-enabled: true
logging-to-file: false
quota-exceeded-switch-project: false
quota-exceeded-switch-preview-model: false
force-model-prefix: ""
oauth-excluded-models: {}
oauth-model-alias: {}

codex-api-key:
  - api-key: your-token-here-v1
    base-url: https://chatgpt.com/backend-api/codex
    priority: 100
    prefix: ""
    headers:
      Chatgpt-Account-Id: ""
    models:
      - name: gpt-5.4
        alias: gpt-5.4
      - name: gpt-5.3-codex
        alias: gpt-5.3-codex
      - name: gpt-5.3-codex-spark
        alias: gpt-5.3-codex-spark
